# call to consumer
GET http://localhost:8081/generate?message=hello HTTP/1.1

###

# call to dapr producer
GET http://localhost:8083/generate?message=mello HTTP/1.1

###

# call to dapr producer via dapr port 
GET http://localhost:9999/generate?message=chello HTTP/1.1

###

# call to springboot producer via NodePort
GET http://localhost:8888/generate?message=camn HTTP/1.1
