# call to consumer
GET http://localhost:8888/httppost?message=hello HTTP/1.1

###

# call to dapr producer
GET http://localhost:8888/generate?message=killo HTTP/1.1

###

# call to dapr pubsub producer
GET http://localhost:8181/generate?message=nillo HTTP/1.1

###

# call to dapr pubsub http producer
GET http://localhost:8888/httppost?message=chillojkh HTTP/1.1

###

# call to dapr producer via dapr port 
GET http://localhost:9999/generate?message=bhillo HTTP/1.1

###

# call to springboot producer via NodePort
GET http://localhost:30091/generate?message=camn HTTP/1.1

###

# Post ot azure func
POST http://localhost:7777/api/hello HTTP/1.1
content-type: application/json

{
    "name": "sample"
}

###

# Post to dapr consumer
POST http://localhost:9999/sample123 HTTP/1.1
content-type: application/json

{
    "name": "sample"
}

###

# port forwarded request to fabricam-functions
GET http://localhost:8989/sample123?name=Functions HTTP/1/1

###

# Post ot azure func
POST http://localhost:8989/sample123 HTTP/1.1
content-type: application/json

{
    "name": "sample"
}

###
# sending an OPTIONS call to azure function
OPTIONS http://localhost:8989/sample123 HTTP/1.1