apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pubsub-dapr-consumer
  name: pubsub-dapr-consumer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsub-dapr-consumer
  strategy: {}
  template:
    metadata:
      labels:
        app: pubsub-dapr-consumer
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "pubsub-dapr-consumer"
        dapr.io/app-port: "3000"  
    spec:
      containers:
      - image: k3d-registry.localhost:5000/pubsub-dapr-consumer
        name: pubsub-dapr-consumer
        ports:
        - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: pubsub-dapr-consumer-service
  name: pubsub-dapr-consumer-service
spec:
  ports:
  - name: 3000-3000
    port: 3020
    protocol: TCP
    targetPort: 3000
  selector:
    app: pubsub-dapr-consumer

