apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: springboot-producer
  name: springboot-producer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-producer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: springboot-producer
      # annotations:
      #   dapr.io/enabled: "true"
      #   dapr.io/app-id: "springboot-producer"
      #   dapr.io/log-level: "debug"  
    spec:
      containers:
      - image: k3d-registry.localhost:5000/springboot-producer
        name: springboot-producer
        resources: {}
status: {}

---


apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: springboot-producer-service
  name: springboot-producer-service
spec:
  ports:
  - name: 8081-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 30090
  selector:
    app: springboot-producer-service
  type: NodePort
status:
  loadBalancer: {}
